---

- name: Deploy app
  community.docker.docker_container:
    name: devops-example-app
    image: hexletcomponents/devops-example-app
    ports:
      - "80:5000"
    restart_policy: always
    restart: yes
    pull: yes
    container_default_behavior: no_defaults
    env:
      SERVER_MESSAGE: "{{ server_message }}"

- name: Set monitoring
  include_role:
    name: datadog.datadog
