---

- name: Login into DockerHub
  community.docker.docker_login:
    username: "{{ docker_user }}"
    password: "{{ docker_password }}"

- name: Deploy app
  community.docker.docker_container:
    name: devops-example-app
    image: dzencot/test
    ports:
      - "80:5000"
    env:
      SERVER_MESSAGE: "{{ server_message }}"

- name: Set monitoring
  include_role:
    name: datadog.datadog
  # vars:
  #   datadog_api_key: "{{ datadog_api_key }}"
  #   datadog_app_key: "{{ datadog_app_key }}"
  #   datadog_site: "datadoghq.eu"
