---

- name: Prepare servers with terraform
  community.general.terraform:
    project_path: "{{ terraform_path }}"
    state: present
  register: terraform_result

- name: Print terraform result
  debug:
    msg: "{{ terraform_result }}"

- name: Update inventory
  template:
    src: inventory.ini
    dest: ./inventory.ini
